
data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/*ubuntu-bionic-18.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-2"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_description = "from {{ .SourceAMI }}"
  ami_name        = "packer_AWS ${local.timestamp}"
  instance_type   = "t2.micro"
  region          = "us-east-2"
  source_ami      = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username    = "ubuntu"
  tags = {
    Base_AMI_Name = "{{ .SourceAMIName }}"
    Extra         = "<no value>"
    OS_Version    = "Ubuntu"
    Release       = "Latest"
    Sistema       = "Metal.corp"
    Tipo          = "Homologacao"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "ansible" {
    ansible_env_vars = ["ANSIBLE_HOST_KEY_CHECKING=False"]
    extra_arguments  = ["--extra-vars", "ansible_python_interpreter=/usr/bin/python3"]
    playbook_file    = "./playbook.yml"
    user             = "ubuntu"
  }

  provisioner "shell" {
      inline = [
        "echo provisioning all the things",
        "echo the value of 'corporation' is 'Metal.Corp'",
      ]
      pause_before = "10s"
  }
}
